version: '3'

services:
  web:
    container_name: web
    restart: always
    build: .
    command: npm run start
    ports:
      - 5000:5000
    volumes:
      - ./:/app
    depends_on:
      - mongo
    links:
      - mongo
    networks:
      - nginx-proxy
      - default

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
    networks:
      - nginx-proxy
      - default

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web
    networks:
      - nginx-proxy
      - default

volumes:
  data:

networks:
  nginx-proxy:
