version: '3'

services:
  web:
    container_name: web
    restart: always
    build: .
    command: npm run start
    ports:
      - 5000:5000
    volumes:
      - ./:/app
    depends_on:
      - mongo
    links:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - data:/data/db

volumes:
  data:
